---
title: "Per Cluster Analysis"
author: "`r getOption('author')`"
date: "`r Sys.Date()`"
bibliography: bibliography.bib
params:
    seurat_file: "data/2018-06-18/seurat.rda"
    interesting_groups: "genotype"
---

```{r setup, cache=FALSE, message=FALSE, warning=FALSE}
source("_setup.R")
seurat_name <- load(params$seurat_file)
seurat <- get(seurat_name)
```

```{r header, child="_header.Rmd", eval=file.exists("_header.Rmd")}
```



# Seurat diagnostics {.tabset}

```{r seurat_diagnostics}
mdHeader("PrintPCAParams")
PrintPCAParams(seurat)

mdHeader("PrintFindClustersParams")
PrintFindClustersParams(seurat)

mdHeader("PrintTSNEParams")
PrintTSNEParams(seurat)

mdHeader("PrintSNNParams")
PrintSNNParams(seurat)
```



# t-SNE plots {.tabset}

```{r tsne}
mdHeader("cluster")
TSNEPlot(
    seurat,
    do.label = TRUE,
    group.by = "ident",
    label.size = 6
)

mdHeader("sampleName")
TSNEPlot(
    seurat,
    do.label = TRUE,
    group.by = "sampleName",
    label.size = 6
)

mdHeader(params$interesting_groups)
TSNEPlot(
    seurat,
    do.label = TRUE,
    group.by = params$interesting_groups,
    label.size = 6
)
```



# PC cluster bias

Let's check the coloring of the clusters according to each principal component included in the analysis. Cluster specificity here can indicate that a specific PC is driving the structure for that individual cluster.

```{r pc_cluster_bias, fig.height=10, fig.width=10}
pc <- seurat %>%
    .@calc.params %>%
    .[["RunTSNE"]] %>%
    .[["dims.use"]] %>%
    paste0("PC", .)
FeaturePlot(
    seurat,
    cols.use = c("purple", "darkgray"),
    features.plot = pc,
    nCol = 3
)
```



# Cells per cluster {.tabset}

```{r per_cluster, fig.height=12, fig.width=6, results="asis"}
ident <- levels(seurat@ident)
lapply(seq_along(ident), function(a) {
    cluster_id <- ident[[a]]
    intgroup <- params$interesting_groups
    title <- paste("cluster", cluster_id)
    writeLines(c(
        "", "",
        paste("##", title),
        "", ""
    ))
    object <- SubsetData(seurat, ident.use = cluster_id)
    n <- ncol(object@data)
    
    # Plots
    p1 <- TSNEPlot(
        object,
        do.return = TRUE,
        group.by = "sampleName"
    ) +
        labs(
            title = tolower(title),
            subtitle = paste("n =", n)
        ) +
        theme(legend.position = "bottom")
    p2 <- TSNEPlot(
        object,
        do.return = TRUE,
        group.by = intgroup
    ) +
        ggtitle(intgroup) +
        theme(legend.position = "bottom")
    plot_grid(p1, p2, labels = "auto", ncol = 1L, nrow = 2L) %>%
        show()
    
    # Tables
    master <- object@meta.data %>%
        as.data.frame() %>%
        .[, c("sampleName", intgroup)] %>%
        rownames_to_column()
    sample_stats <- master %>%
        arrange(.data[["sampleName"]]) %>%
        group_by(.data[["sampleName"]]) %>%
        summarize(count = n()) %>%
        mutate(pct = .data[["count"]] / sum(.data[["count"]]))
    intgroup_stats <- master %>%
        arrange(.data[[intgroup]]) %>%
        group_by(.data[[intgroup]]) %>%
        summarize(count = n()) %>%
        mutate(pct = .data[["count"]] / sum(.data[["count"]]))
    kable(
        sample_stats,
        caption = paste0(title, ": sampleName"),
        digits = 2L
    ) %>%
        show()
    kable(
        intgroup_stats,
        caption = paste0(title, ": ", intgroup),
        digits = 2L
    ) %>%
        show()
}) %>%
    invisible
```



```{r footer, child="_footer.Rmd", eval=file.exists("_footer.Rmd")}
```
