---
title: "Gene-Gene Plots"
author: "`r getOption('author')`"
date: "`r Sys.Date()`"
---

```{r setup, cache=FALSE, message=FALSE, results="hide"}
source("setup.R")
library(Seurat)
library(tidyverse)
data(bcbFilteredSeurat)
seurat <- bcbFilteredSeurat
meta <- seurat@meta.data %>%
    camel %>%
    select(sampleName, genotype)
genes <- c(
    "Cd24a",
    "Muc1",
    "Acta2",
    "Krt14",
    "Ar",
    "Gata3")
colors <- c(
    "#005493",  # 6189  WT   blue - ocean
    "#941100",  # 6191  Het  red - cayenne
    "#FF2600",  # 6207  Het  red - maraschino
    "#0096FF",  # 6209  WT   blue - aqua
    "#FF7E79",  # 6308  Het  red - salmon
    "#76D6FF")  # 6311  WT   blue - sky
data_unscaled <- FetchData(
    seurat,
    vars.all = genes,
    use.scaled = FALSE) %>%
    as.data.frame %>%
    cbind(meta)
data_scaled <- FetchData(
    seurat,
    vars.all = genes,
    use.scaled = TRUE) %>%
    as.data.frame %>%
    cbind(meta)

theme_set(theme_light(base_size = 14))
theme_update(legend.position = "bottom")
```

Scaled data uses the scale factors generated by `ScaleData()` when we regressed out technical variation due to differing `nUMI`, `nGene`, and `mitoRatio` (see Seurat report).



# Cd24a vs. Muc1

```{r}
GenePlot(
    seurat,
    gene1 = "Cd24a",
    gene2 = "Muc1",
    use.scaled = FALSE)
GenePlot(
    seurat,
    gene1 = "Cd24a",
    gene2 = "Muc1",
    use.scaled = TRUE)
```

```{r}
ggplot(
    data_unscaled,
    aes(x = Cd24a,
        y = Muc1,
        color = sampleName)) +
    geom_point(size = 2) +
    scale_color_manual(values = colors) +
    ggtitle("unscaled")
ggplot(
    data_scaled,
    aes(x = Cd24a,
        y = Muc1,
        color = sampleName)) +
    geom_point(size = 2) +
    scale_color_manual(values = colors) +
    ggtitle("scaled")
```



# Acta2 vs. Krt14

```{r}
GenePlot(
    seurat,
    gene1 = "Acta2",
    gene2 = "Krt14",
    use.scaled = FALSE)
GenePlot(
    seurat,
    gene1 = "Acta2",
    gene2 = "Krt14",
    use.scaled = TRUE)
```

```{r}
ggplot(
    data_unscaled,
    aes(x = Acta2,
        y = Krt14,
        color = sampleName)) +
    geom_point(size = 2) +
    scale_color_manual(values = colors) +
    ggtitle("unscaled")
ggplot(
    data_scaled,
    aes(x = Acta2,
        y = Krt14,
        color = sampleName)) +
    geom_point(size = 2) +
    scale_color_manual(values = colors) +
    ggtitle("scaled")
```



# Ar vs. Gata3

```{r}
GenePlot(
    seurat,
    gene1 = "Ar",
    gene2 = "Gata3",
    use.scaled = FALSE)
GenePlot(
    seurat,
    gene1 = "Ar",
    gene2 = "Gata3",
    use.scaled = TRUE)
```

```{r}
ggplot(
    data_unscaled,
    aes(x = Ar,
        y = Gata3,
        color = sampleName)) +
    geom_point(size = 2) +
    scale_color_manual(values = colors) +
    ggtitle("unscaled")
ggplot(
    data_scaled,
    aes(x = Ar,
        y = Gata3,
        color = sampleName)) +
    geom_point(size = 2) +
    scale_color_manual(values = colors) +
    ggtitle("scaled")
```
